// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jufbqkpfjezovqyidgmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1ZmJxa3BmamV6b3ZxeWlkZ21nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMTUxODgsImV4cCI6MjA2NDg5MTE4OH0.GUxbLRk3nNDkU6f5C6o44tdJ9z7K-lqeC-S9DL8aVMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);